import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'sa', name: 'Sanskrit', native: 'संस्कृतम्' },
  { code: 'ur', name: 'Urdu', native: 'اردو' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'ja', name: 'Japanese', native: '日本語' },
  { code: 'ko', name: 'Korean', native: '한국어' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'zh', name: 'Chinese', native: '中文' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
];

export const UI_LABELS = {
  en: {
    welcome: 'Divine Wisdom for Modern Minds',
    startLearning: 'START LEARNING',
    gitaReels: 'GITA REELS',
    kidsParadise: 'Kids Paradise',
    safeFunLearning: 'Safe & Fun Learning',
    divineCinema: 'Divine Cinema',
    trendingNow: 'Trending Now',
    aiSearch: 'AI Search...',
    save: 'Save',
    share: 'Share',
    enterCinema: 'Enter Divine Cinema',
    spiritualPath: 'Spiritual Path',
    dailySloka: 'DAILY SLOKA',
    slokaText: '"You have a right to perform your duty, but not to the fruits."',
    backToLibrary: 'Back to Library',
    divineLibrary: 'Divine Library',
    divineLibrarySub: 'Immerse yourself in the eternal wisdom of India through AI-powered chapters and audiobooks.',
    startReading: 'Start Reading',
    chapters: 'Chapters',
    aiMentorTip: 'AI Mentor Tip',
    askAiMentor: 'Ask AI Mentor About This Story',
    listenWithAi: 'Listen with AI',
    stopAiNarration: 'Stop AI Narration',
    saveStory: 'Save Story',
    saved: 'Saved',
    spiritualTakeaways: 'Spiritual Takeaways',
    translatingWisdom: 'Translating Divine Wisdom...',
    seekingWisdom: 'Seeking wisdom...',
    meaning: 'Meaning',
    insight: 'Modern Insight',
    wisdom: 'Applied Wisdom',
    dailyApplication: 'Daily Application',
    krishnaGuidance: 'Krishna\'s Guidance',
    practicalSolution: 'Practical Solution',
    aiGuidance: 'AI Mentor Guidance',
    curatedVerses: 'Curated Verses',
    aiMentor: 'AI Mentor',
    divineGuidance: 'Divine Guidance',
    seekingGuidance: 'Seeking guidance in Lord Krishna\'s eternal words...',
    stress: 'Stress',
    fear: 'Fear',
    anger: 'Anger',
    confusion: 'Confusion',
    motivation: 'Motivation',
    anxiety: 'Anxiety',
    sadness: 'Sadness',
    loneliness: 'Loneliness',
    selfDoubt: 'Self-Doubt',
    discipline: 'Discipline',
    depression: 'Depression',
    focus: 'Focus',
    overthinking: 'Overthinking',
    failure: 'Failure',
    success: 'Success',
    relationships: 'Relationships',
    purpose: 'Purpose of Life',
    peace: 'Peace',
    confidence: 'Confidence',
    relatedVerses: 'Related Verses',
    relatedStories: 'Related Stories',
    stop: 'Stop',
    listenWithAi: 'Listen with AI',
    krishnaVoice: 'Krishna Voice',
    ramVoice: 'Ram Voice',
    hanumanVoice: 'Hanuman Voice',
    arjunaVoice: 'Arjuna Voice',
    recommendedVideo: 'Recommended Video',
    divineWisdom: 'Divine Wisdom',
    gitaQuote: 'A verse from the Bhagavad Gita to guide your day',
    previousDay: 'Previous Day',
    apiConfig: 'API Config',
    hide: 'Hide',
    choose: 'Choose',
    selectDate: 'Select Date',
    sacredVerse: 'Sacred Verse',
    chapter: 'Chapter',
    verse: 'Verse',
    listen: 'Listen',
    copy: 'Copy',
    copied: 'Copied!',
    saveVerse: 'Save Verse',
    savedVerse: 'Saved Verse',
    enableNotifications: 'Enable Notifications',
    notificationsOn: 'Notifications On',
    relatedTopics: 'Related Topics',
    savedDailyVerses: 'Saved Daily Verses',
    open: 'Open',
    previous: 'Previous'
  },
  hi: {
    welcome: 'आधुनिक दिमागों के लिए दिव्य ज्ञान',
    startLearning: 'सीखना शुरू करें',
    gitaReels: 'गीता रील्स',
    kidsParadise: 'किड्स पैराडाइज',
    safeFunLearning: 'सुरक्षित और मजेदार सीखना',
    divineCinema: 'दिव्य सिनेमा',
    trendingNow: 'अभी ट्रेंडिंग',
    aiSearch: 'एआई खोज...',
    follow: 'फॉलो करें',
    save: 'सहेजें',
    share: 'साझा करें',
    enterCinema: 'दिव्य सिनेमा में प्रवेश करें',
    spiritualPath: 'आध्यात्मिक पथ',
    dailySloka: 'दैनिक श्लोक',
    slokaText: '"आपको अपना कर्तव्य निभाने का अधिकार है, लेकिन उसके फलों पर नहीं।"',
    backToLibrary: 'लाइब्रेरी में वापस जाएं',
    divineLibrary: 'दिव्य लाइब्रेरी',
    divineLibrarySub: 'एआई-संचालित अध्यायों और ऑडियोबुक्स के माध्यम से भारत के शाश्वत ज्ञान में डूब जाएं।',
    startReading: 'पढ़ना शुरू करें',
    chapters: 'अध्याय',
    aiMentorTip: 'एआई संरक्षक टिप',
    askAiMentor: 'इस कहानी के बारे में एआई संरक्षक से पूछें',
    listenWithAi: 'एआई के साथ सुनें',
    stopAiNarration: 'एआई वर्णन रोकें',
    saveStory: 'कहानी सहेजें',
    saved: 'सहेजा गया',
    spiritualTakeaways: 'आध्यात्मिक सीख',
    translatingWisdom: 'दिव्य ज्ञान का अनुवाद हो रहा है...',
    seekingWisdom: 'ज्ञान की खोज...',
    meaning: 'अर्थ',
    insight: 'आधुनिक अंतर्दृष्टि',
    wisdom: 'व्याవहारिक ज्ञान',
    dailyApplication: 'दैनिक अनुप्रयोग',
    krishnaGuidance: 'कृष्ण का मार्गदर्शन',
    practicalSolution: 'व्यावहारिक समाधान',
    aiGuidance: 'AI संरक्षक मार्गदर्शन',
    curatedVerses: 'संग्रहित श्लोक',
    aiMentor: 'AI संरक्षक',
    divineGuidance: 'दिव्य मार्गदर्शन',
    seekingGuidance: 'भगवान कृष्ण के शाश्वत शब्दों में मार्गदर्शन खोज रहे हैं...',
    stress: 'तनाव',
    fear: 'डर',
    anger: 'क्रोध',
    confusion: 'भ्रम',
    motivation: 'प्रेरणा',
    anxiety: 'चिंता',
    sadness: 'उदासी',
    loneliness: 'अकेलापन',
    selfDoubt: 'आत्म-संदेह',
    discipline: 'अनुशासन',
    depression: 'अवसाद',
    focus: 'एकाग्रता',
    overthinking: 'अतिविचार',
    failure: 'असफलता',
    success: 'सफलता',
    relationships: 'संबंध',
    purpose: 'जीवन का उद्देश्य',
    peace: 'शांति',
    confidence: 'आत्मविश्वास',
    relatedVerses: 'संबंधित श్లోక',
    relatedStories: 'संबंधित कहानियाँ',
    stop: 'रोकें',
    listenWithAi: 'AI के साथ सुनें',
    krishnaVoice: 'कृष्ण स्वर',
    ramVoice: 'राम स्वर',
    hanumanVoice: 'हनుమాన్ स्वर',
    arjunaVoice: 'अर्जुन स्वर',
    recommendedVideo: 'अनुशंसित वीडियो',
    divineWisdom: 'दिव्य ज्ञान',
    gitaQuote: 'आपके दिन का मार्गदर्शन करने के लिए भगवद गीता का एक श्लोक',
    previousDay: 'पिछला दिन',
    apiConfig: 'API कॉन्फ़ిగ',
    hide: 'छिपाएं',
    choose: 'चुनें',
    selectDate: 'तारीख चुनें',
    sacredVerse: 'पवित्र श्लोक',
    chapter: 'अध्याय',
    verse: 'श्लोक',
    listen: 'सुनें',
    copy: 'कॉपी करें',
    copied: 'कॉपी किया गया!',
    saveVerse: 'श्लोक सहेजें',
    savedVerse: 'सहेजा गया श्लोक',
    enableNotifications: 'सूचनाएं चालू करें',
    notificationsOn: 'सूचनाएं चालू हैं',
    relatedTopics: 'संबंधित विषय',
    savedDailyVerses: 'सहेजे गए दैनिक श्लोक',
    open: 'खोलें',
    previous: 'पिछला'
  },
  te: {
    welcome: 'ఆధునిక మనస్సుల కోసం దైవిక జ్ఞానం',
    startLearning: 'నేర్చుకోవడం ప్రారంభించండి',
    gitaReels: 'గీతా రీల్స్',
    kidsParadise: 'కిడ్స్ ప్యారడైజ్',
    safeFunLearning: 'సురక్షితమైన మరియు సరదా అభ్యాసం',
    divineCinema: 'దైవిక సినిమా',
    trendingNow: 'ప్రస్తుతం ట్రెండింగ్‌లో ఉంది',
    aiSearch: 'AI శోధన...',
    follow: 'అనుసరించండి',
    save: 'సేవ్ చేయండి',
    share: 'షేర్ చేయండి',
    enterCinema: 'దైవిక సినిమాలోకి ప్రవేశించండి',
    spiritualPath: 'ఆధ్యాత్మిక మార్గం',
    dailySloka: 'దైనందిన శ్లోకం',
    slokaText: '"నీ కర్తవ్యాన్ని నిర్వహించే హక్కు నీకు ఉంది, కానీ ఫలితాలపై కాదు."',
    meaning: 'అర్థం',
    insight: 'ఆధునిక అవగాహన',
    wisdom: 'ఆచరణాత్మక జ్ఞానం',
    dailyApplication: 'నిత్య జీవితంలో అన్వయం',
    krishnaGuidance: 'శ్రీకృష్ణుని మార్గదర్శకత్వం',
    practicalSolution: 'ఆచరణాత్మక పరిష్కారం',
    aiGuidance: 'AI మెంటర్ గైడెన్స్',
    curatedVerses: 'ఎంపిక చేసిన శ్లోకాలు',
    aiMentor: 'AI మెంటర్',
    divineGuidance: 'దైవిక మార్గదర్శకత్వం',
    seekingGuidance: 'శ్రీకృష్ణుని అమృత వాక్కులలో పరిష్కారం వెతుకుతున్నాము...',
    stress: 'ఒత్తిడి',
    fear: 'భయం',
    anger: 'కోపం',
    confusion: 'సందిగ్ధత',
    motivation: 'ప్రేరణ',
    anxiety: 'ఆందోళన',
    sadness: 'విచారం',
    loneliness: 'ఒంటరితనం',
    selfDoubt: 'ఆత్మసందేహం',
    discipline: 'క్రమశిక్షణ',
    depression: 'నిస్పృహ',
    focus: 'ఏకాగ్రత',
    overthinking: 'అతిగా ఆలోచించడం',
    failure: 'ఓటమి',
    success: 'విజయం',
    relationships: 'సంబంధ బాంధవ్యాలు',
    purpose: 'జీవిత పరమార్థం',
    peace: 'శాంతి',
    confidence: 'ఆత్మవిశ్వాసం',
    relatedVerses: 'సంబంధిత శ్లోకాలు',
    relatedStories: 'సంబంధిత కథలు',
    stop: 'ఆపు',
    listenWithAi: 'AI తో వినండి',
    krishnaVoice: 'శ్రీకృష్ణుని స్వరం',
    ramVoice: 'శ్రీరాముని స్వరం',
    hanumanVoice: 'హనుమంతుని స్వరం',
    arjunaVoice: 'అర్జునుని స్వరం',
    recommendedVideo: 'సిఫార్సు చేయబడిన వీడియో',
    divineWisdom: 'దైవిక జ్ఞానం',
    gitaQuote: 'మీ రోజును నడిపించడానికి భగవద్గీత నుండి ఒక శ్లోకం',
    previousDay: 'మునుపటి రోజు',
    apiConfig: 'API కాన్ఫిగ్',
    hide: 'దాచు',
    choose: 'ఎంచుకోండి',
    selectDate: 'తేదీని ఎంచుకోండి',
    sacredVerse: 'పవిత్ర శ్లోకం',
    chapter: 'అధ్యాయం',
    verse: 'శ్లోకం',
    listen: 'వినండి',
    copy: 'కాపీ',
    copied: 'కాపీ చేయబడింది!',
    saveVerse: 'శ్లోకాన్ని సేవ్ చేయండి',
    savedVerse: 'సేవ్ చేసిన శ్లోకం',
    enableNotifications: 'నోటిఫికేషన్లను ఆన్ చేయండి',
    notificationsOn: 'నోటిఫికేషన్లు ఆన్‌లో ఉన్నాయి',
    relatedTopics: 'సంబంధిత అంశాలు',
    savedDailyVerses: 'సేవ్ చేసిన దైనందిన శ్లోకాలు',
    open: 'ఓపెన్',
    previous: 'మునుపటి'
  },
  ta: {
    welcome: 'நவீன மனங்களுக்கான தெய்வீக ஞானம்',
    startLearning: 'கற்றலைத் தொடங்கு',
    gitaReels: 'கீதா ரீல்ஸ்',
    kidsParadise: 'குழந்தைகள் சொர்க்கம்',
    safeFunLearning: 'பாதுகாப்பான மற்றும் வேடிக்கையான கற்றல்',
    divineCinema: 'தெய்வீக சினிமா',
    trendingNow: 'இப்போது பிரபலமானது',
    aiSearch: 'AI தேடல்...',
    follow: 'பின்தொடர்',
    save: 'சேமி',
    share: 'பகிர்',
    enterCinema: 'தெய்வீக சினிமாவில் நுழையுங்கள்',
    spiritualPath: 'ஆன்மீக பாதை',
    dailySloka: 'தினசரி ஸ்லோகம்',
    slokaText: '"உங்கள் கடமையைச் செய்ய உங்களுக்கு உரிமை உண்டு, ஆனால் அதன் பலன்களுக்கு அல்ல."',
    meaning: 'பொருள்',
    insight: 'நவீன நுண்ணறிவு',
    wisdom: 'நடைமுறை ஞானம்'
  },
  ur: {
    welcome: 'جدید ذہنوں کے لیے الہی حکمت',
    startLearning: 'سیکھنا شروع کریں',
    gitaReels: 'گیتا ریلز',
    kidsParadise: 'بچوں کی جنت',
    safeFunLearning: 'محفوظ اور تفریحی سیکھنا',
    divineCinema: 'الہی سینما',
    trendingNow: 'ابھی ٹرینڈنگ',
    aiSearch: 'اے آئی سرچ...',
    follow: 'فالو کریں',
    save: 'محفوظ کریں',
    share: 'شیئر کریں',
    enterCinema: 'الہی سینما میں داخل ہوں',
    spiritualPath: 'روحانی راستہ',
    dailySloka: 'یومیہ شلوک',
    slokaText: '"آپ کو اپنا فرض ادا کرنے کا حق ہے، لیکن اس کے پھلوں پر نہیں۔"',
  },
  ml: {
    welcome: 'ആധുനിക മനസ്സുകൾക്കുള്ള ദൈവിക ജ്ഞാനം',
    startLearning: 'പഠനം ആരംഭിക്കുക',
    gitaReels: 'ഗീത റീൽസ്',
    kidsParadise: 'കുട്ടികളുടെ സ്വർഗ്ഗം',
    safeFunLearning: 'സുരക്ഷിതവും രസകരവുമായ പഠനം',
    divineCinema: 'ദൈവിക സിനിമ',
    trendingNow: 'ഇപ്പോൾ ട്രെൻഡ് ചെയ്യുന്നു',
    aiSearch: 'AI തിരയൽ...',
    follow: 'പിന്തുടരുക',
    save: 'സംരക്ഷിക്കുക',
    share: 'പങ്കിടുക',
    enterCinema: 'ദൈവിക സിനിമയിൽ പ്രവേശിക്കുക',
    spiritualPath: 'ആദ്ധ്യാത്മിക പാത',
    dailySloka: 'ദൈനിക ശ്ലോകം',
    slokaText: '"നിങ്ങൾക്ക് കർത്തവ്യം ചെയ്യാൻ അവകാശമുണ്ട്, ഫലങ്ങളിൽ അല്ല."',
    meaning: 'അർത്ഥം',
    insight: 'ആധുനിക ഉൾക്കാഴ്ച',
    wisdom: 'പ്രായോഗിക ജ്ഞാനം'
  },
  ru: {
    welcome: 'Божественная мудрость для современных умов',
    startLearning: 'НАЧАТЬ ОБУЧЕНИЕ',
    gitaReels: 'ГИТА РИЛС',
    kidsParadise: 'Детский рай',
    safeFunLearning: 'Безопасное и веселое обучение',
    divineCinema: 'Божественный кинотеатр',
    trendingNow: 'Сейчас в тренде',
    aiSearch: 'AI поиск...',
    follow: 'Подписаться',
    save: 'Сохранить',
    share: 'Поделиться',
    enterCinema: 'Войти в Божественный кинотеатр',
    spiritualPath: 'Духовный путь',
  },
  pt: {
    welcome: 'Sabedoria Divina para Mentes Modernas',
    startLearning: 'COMEÇAR A APRENDER',
    gitaReels: 'REELS DA GITA',
    kidsParadise: 'Paraíso das Crianças',
    safeFunLearning: 'Aprendizado Seguro e Divertido',
    divineCinema: 'Cinema Divino',
    trendingNow: 'Bombando agora',
    aiSearch: 'Pesquisa AI...',
    follow: 'Seguir',
    save: 'Salvar',
    share: 'Compartilhar',
    enterCinema: 'Entrar no Cinema Divino',
    spiritualPath: 'Caminho Espiritual',
    dailySloka: 'SLOKA DIÁRIO',
    slokaText: '"Você tem o direito de cumprir seu dever, mas não aos frutos."',
  },
  kn: {
    welcome: 'ಆಧುನಿಕ ಮನಸ್ಸುಗಳಿಗೆ ದೈವಿಕ ಜ್ಞಾನ',
    startLearning: 'ಕಲಿಕೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    gitaReels: 'ಗೀತಾ ರೀಲ್ಸ್',
    kidsParadise: 'ಮಕ್ಕಳ ಸ್ವರ್ಗ',
    safeFunLearning: 'ಸುರಕ್ಷಿತ ಮತ್ತು ಮೋಜಿನ ಕಲಿಕೆ',
    divineCinema: 'ದೈವಿಕ ಸಿನೆಮಾ',
    trendingNow: 'ಈಗ ಟ್ರೆಂಡಿಂಗ್',
    aiSearch: 'AI ಹುಡುಕಾಟ...',
    follow: 'ಅನುಸರಿಸಿ',
    save: 'ಉಳಿಸಿ',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    enterCinema: 'ದೈವಿಕ ಸಿನೆಮಾವನ್ನು ಪ್ರವೇಶಿಸಿ',
    spiritualPath: 'ಆಧ್ಯಾತ್ಮಿಕ ಹಾದಿ',
    dailySloka: 'ದೈನಂದಿನ ಶ್ಲೋಕ',
    slokaText: '"ನಿಮ್ಮ ಕರ್ತವ್ಯವನ್ನು ಮಾಡಲು ನಿಮಗೆ ಹಕ್ಕಿದೆ, ಆದರೆ ಫಲಿತಾಂಶದ ಮೇಲಲ್ಲ."',
    meaning: 'ಅರ್ಥ',
    insight: 'ಆಧುನಿಕ ಒಳನೋಟ',
    wisdom: 'ಪ್ರಾಯೋಗಿಕ ಜ್ಞಾನ'
  },
  sa: {
    welcome: 'आधुनिकमनसां कृते दिव्यज्ञानम्',
    startLearning: 'अधिगमं आरभत',
    gitaReels: 'गीतारील्स्',
    kidsParadise: 'बालस्वर्गः',
    safeFunLearning: 'सुरक्षितं आनन्ददं च शिक्षणम्',
    divineCinema: 'दिव्यं चलच्चित्रम्',
    trendingNow: 'अधुना प्रचलिताः',
    aiSearch: 'AI अन्वेषणम्...',
    follow: 'अनुसरतु',
    save: 'रक्षतु',
    share: 'वितरतु',
    enterCinema: 'दिव्यं चलच्चित्रं प्रविशतु',
    spiritualPath: 'आध्यात्मिकः मार्गः',
    dailySloka: 'दैनिकश्लोकः',
    slokaText: '"कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥"',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('preferredLanguage') || 'en');

  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  const t = (content, field) => {
    if (!content) return '';
    
    // 1. Check strict translations object (AI Generated)
    if (content.translations && content.translations[language] && content.translations[language][field]) {
      return content.translations[language][field];
    }
    
    // 2. Map language codes to legacy field names
    const legacyMap = {
      en: 'English',
      hi: 'Hindi',
      te: 'Telugu',
      ta: 'Tamil',
      kn: 'Kannada',
      ml: 'Malayalam',
      sa: 'Sanskrit'
    };
    
    const suffix = legacyMap[language];
    if (suffix && content[`${field}${suffix}`]) {
      return content[`${field}${suffix}`];
    }
    
    // 3. Fallback to English suffix
    if (content[`${field}English`]) return content[`${field}English`];
    
    // 4. Final fallback to base field
    return content[field] || '';
  };

  const tLabel = (key) => {
    return UI_LABELS[language]?.[key] || UI_LABELS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tLabel, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
